title: MatchyPatchy User Manual
email: tswanson@sdzwa.org
description: >-
  MatchyPatchy is an open-source GUI tool for human validation of AI-powered animal re-identification.

url: "https://conservationtechlab.github.io"   
baseurl: "/matchypatchy" 
github_username:  conservationtechlab

# Build settings
theme: minima
plugins:
  - jekyll-feed
